// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApi2024;

#nullable disable

namespace ShopApi2024.Migrations
{
    [DbContext(typeof(ShopApi2024Db))]
    [Migration("20240927123947_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopApi2024.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 160, DateTimeKind.Local).AddTicks(1015),
                            Description = "ratione",
                            ImageName = "e1878e9a-a9c0-423e-bc9f-f4c43129ea78.webp",
                            IsDelete = false,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(1090),
                            Description = "Sit tempora officia.\nAliquid et blanditiis quaerat explicabo expedita.\nUnde et culpa.\nEst quod nesciunt unde illo excepturi id ea.\nAssumenda sapiente dolor eligendi dolorem ratione maxime dolorum.\nQuo expedita soluta.",
                            ImageName = "f507920e-1ec6-4c91-a837-91becdcf0bae.webp",
                            IsDelete = false,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(8427),
                            Description = "Voluptatibus aut quia et ut ut iste consequatur voluptate.\nIncidunt magnam saepe unde est praesentium dignissimos consequuntur.\nConsequatur debitis voluptatem.",
                            ImageName = "8dde2a6e-8c61-49b6-98c4-4805a6940aa6.webp",
                            IsDelete = false,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 162, DateTimeKind.Local).AddTicks(7283),
                            Description = "Sint sed dolorem et magnam quidem. Ex adipisci debitis sed saepe autem accusamus ipsam. Inventore sequi quam blanditiis error officia nisi rerum. Dolorem voluptas eos qui ratione voluptas et velit facere ut. Debitis ducimus aperiam qui provident excepturi quos.",
                            ImageName = "822b5b70-dad8-4795-bcaf-06aedaba0d7d.webp",
                            IsDelete = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 163, DateTimeKind.Local).AddTicks(6463),
                            Description = "ut",
                            ImageName = "ea3848f2-d56e-4a3a-a958-210249ab9030.webp",
                            IsDelete = false,
                            Name = "Movies"
                        });
                });

            modelBuilder.Entity("ShopApi2024.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 160, DateTimeKind.Local).AddTicks(1360),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 1.0,
                            ImageName = "bb2a0249-6fbe-4bcd-8f7a-cd003c170845",
                            IsDelete = false,
                            Name = "Generic Wooden Tuna",
                            Price = 126.60m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 160, DateTimeKind.Local).AddTicks(1549),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 20.0,
                            ImageName = "7208ea4f-941e-4409-ac31-05b8d69a83d8",
                            IsDelete = false,
                            Name = "Incredible Rubber Tuna",
                            Price = 33.84m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 160, DateTimeKind.Local).AddTicks(1580),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 38.0,
                            ImageName = "a36b4678-00f1-47cc-ad88-c12861c14c48",
                            IsDelete = false,
                            Name = "Handcrafted Cotton Bacon",
                            Price = 633.61m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 160, DateTimeKind.Local).AddTicks(1605),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 1.0,
                            ImageName = "7ff28a1e-41e1-4f8d-a90c-7402ce46f63a",
                            IsDelete = false,
                            Name = "Gorgeous Fresh Chicken",
                            Price = 303.56m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 160, DateTimeKind.Local).AddTicks(1628),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 6.0,
                            ImageName = "f846e456-e1bf-4468-afd1-689da2c6762b",
                            IsDelete = false,
                            Name = "Awesome Granite Table",
                            Price = 343.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(1468),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 9.0,
                            ImageName = "74d8bf37-0b93-4bb3-bf88-9a49cd0b49ef",
                            IsDelete = false,
                            Name = "Practical Frozen Chair",
                            Price = 217.54m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(1536),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Discount = 2.0,
                            ImageName = "aa726b2a-42d4-4721-a469-6ab84cb010ea",
                            IsDelete = false,
                            Name = "Licensed Fresh Computer",
                            Price = 12.75m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(1600),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 48.0,
                            ImageName = "48eb12a6-d55a-48a1-88ba-3c4eefd51d94",
                            IsDelete = false,
                            Name = "Intelligent Metal Chips",
                            Price = 949.37m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(1667),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 5.0,
                            ImageName = "4045ed59-69c1-479f-ac2f-a0378bbe7611",
                            IsDelete = false,
                            Name = "Small Rubber Computer",
                            Price = 126.97m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(1729),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Discount = 10.0,
                            ImageName = "caefc71a-b58d-4a1a-abc8-10d9cd25374a",
                            IsDelete = false,
                            Name = "Fantastic Metal Fish",
                            Price = 571.07m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(8741),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 28.0,
                            ImageName = "0b46390f-eee7-4396-b857-a2cccc1bde1f",
                            IsDelete = false,
                            Name = "Unbranded Steel Ball",
                            Price = 317.71m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(8872),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 32.0,
                            ImageName = "b748573b-b49e-4d20-b68f-5d7462725a24",
                            IsDelete = false,
                            Name = "Awesome Rubber Chicken",
                            Price = 828.12m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(8954),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 11.0,
                            ImageName = "0f98e287-1d60-4942-b560-35a49ce92873",
                            IsDelete = false,
                            Name = "Handmade Granite Car",
                            Price = 528.87m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(9072),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 44.0,
                            ImageName = "beb9f01a-951e-4ef6-9dda-b3f27df75ce7",
                            IsDelete = false,
                            Name = "Incredible Concrete Fish",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 161, DateTimeKind.Local).AddTicks(9177),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Discount = 47.0,
                            ImageName = "f44f8fd6-292d-471c-afcd-c9202fa7cf0d",
                            IsDelete = false,
                            Name = "Gorgeous Frozen Computer",
                            Price = 629.94m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 162, DateTimeKind.Local).AddTicks(7604),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 11.0,
                            ImageName = "07f4a829-5a68-411e-a9bf-632744923fdd",
                            IsDelete = false,
                            Name = "Generic Wooden Bacon",
                            Price = 612.43m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 162, DateTimeKind.Local).AddTicks(7735),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 2.0,
                            ImageName = "84ba4c12-40de-4e78-9699-c073bc5f7fcd",
                            IsDelete = false,
                            Name = "Refined Rubber Computer",
                            Price = 679.36m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 162, DateTimeKind.Local).AddTicks(7851),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Discount = 17.0,
                            ImageName = "6b73dfa2-6816-4805-b641-c7370b1c01a9",
                            IsDelete = false,
                            Name = "Handcrafted Plastic Bacon",
                            Price = 716.43m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 162, DateTimeKind.Local).AddTicks(7969),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 40.0,
                            ImageName = "e60b94b8-6361-4fad-a73f-9e6903c4fc43",
                            IsDelete = false,
                            Name = "Sleek Fresh Hat",
                            Price = 932.34m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 162, DateTimeKind.Local).AddTicks(8083),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 36.0,
                            ImageName = "afce37b3-9935-4187-a545-9d27126bc09d",
                            IsDelete = false,
                            Name = "Fantastic Plastic Gloves",
                            Price = 22.56m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 163, DateTimeKind.Local).AddTicks(6827),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 29.0,
                            ImageName = "463d73b0-08ca-4d11-afe2-3697ff41d77d",
                            IsDelete = false,
                            Name = "Unbranded Granite Shirt",
                            Price = 846.66m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 163, DateTimeKind.Local).AddTicks(7038),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 2.0,
                            ImageName = "1de4462c-e96e-4add-b36b-2f828ee9e0ee",
                            IsDelete = false,
                            Name = "Licensed Wooden Computer",
                            Price = 920.43m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 163, DateTimeKind.Local).AddTicks(7075),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Discount = 22.0,
                            ImageName = "085a7dce-75a1-4c53-93c1-afab06fc6ddc",
                            IsDelete = false,
                            Name = "Small Granite Bacon",
                            Price = 438.97m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 163, DateTimeKind.Local).AddTicks(7112),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Discount = 48.0,
                            ImageName = "b2107a5a-d46f-466c-8aa5-a066aa0121d0",
                            IsDelete = false,
                            Name = "Awesome Rubber Hat",
                            Price = 889.78m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreationTime = new DateTime(2024, 9, 27, 15, 39, 47, 163, DateTimeKind.Local).AddTicks(7150),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 49.0,
                            ImageName = "dd216f78-23c2-47ef-bb7c-1b13314a3475",
                            IsDelete = false,
                            Name = "Refined Wooden Salad",
                            Price = 401.34m
                        });
                });

            modelBuilder.Entity("ShopApi2024.Entities.Product", b =>
                {
                    b.HasOne("ShopApi2024.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopApi2024.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
